import assert from 'node:assert/strict';
import { Outbreak, S, I, R } from '../src/virus.js';
import { setSinglePlayer, activeSides, sideAt, gameRect } from '../src/game-view.js';
import { SpreaderAI } from '../src/spreader-ai.js';
const agents = Array.from({length:100}, (_,i) => ({x:i,z:0,out:true,threshold:0.5}));
const g = new Outbreak({ agents });
g.phase = 'running'; g.points.spreader = g.points.curber = 1000;
assert.equal(g.available('festival'), false);
g.soloRole = 'spreader'; g.ever = 19;
assert.equal(g.available('festival'), false);
g.ever = 40; agents[0].inf = I;
assert.ok(g.act('festival', 0, 0));
assert.equal(g.parties[0].members.length, 100);
assert.equal(g.act('festival', 0, 0), false);
assert.ok(g.act('relocate', 800, 800));
assert.equal(agents[0].x, 800);
assert.ok(g.act('blackout')); assert.ok(g.act('mutation'));
assert.equal(g.seed(0,0), false);
g.soloRole = 'curber'; agents.forEach(p => p.inf = S);
for (const p of agents.slice(0,24)) p.inf = R;
assert.equal(g.available('barrier'), false);
agents[24].inf = R;
const before = g.points.curber;
assert.equal(g.addBarrier([{x:0,z:0}]), false);
assert.equal(g.points.curber, before);
assert.ok(g.addBarrier([{x:50,z:-100}, {x:50,z:100}]));
assert.ok(g.blockedContact({x:40,z:0}, {x:60,z:0}));
assert.equal(g.blockedContact({x:0,z:0}, {x:10,z:0}), false);
assert.equal(g.addBarrier([{x:20,z:0},{x:20,z:100}]), false);
assert.equal(g.barriers[0].until, Infinity);
g.barriers[0].until = 1200;
g.time = 1201;
assert.equal(g.blockedContact({x:40,z:0}, {x:60,z:0}), false);
setSinglePlayer(true,'curber');
assert.deepEqual(activeSides(), ['curber']);
assert.ok(gameRect('curber',1440,900).x>0);
assert.equal(sideAt(500,200,1440,900),'curber');
assert.equal(sideAt(10,200,1440,900),null);
assert.equal(gameRect('curber',1440,900).height,788);
assert.equal(sideAt(1400,200,1440,900),null);
setSinglePlayer(false);
const ai = new SpreaderAI(g); ai.step();
assert.ok(g.actionLog.some(e => e.kind === 'antimask' || e.kind === 'antivaxx'));
console.log('Solo milestones, powers, cooldowns, barrier crossing/expiry, government geometry and AI passed.');

const basic = new Outbreak({ agents: Array.from({length:100},(_,i)=>({x:i,z:0,out:true})) });
const multiplayerCooldown = basic.action('party').cooldown;
basic.configureSolo('spreader');
assert.ok(basic.action('party').cooldown < multiplayerCooldown);
basic.ever = 10; basic.time = 1799;
const early = basic.transmissionBoost(); basic.time = 1800;
assert.ok(basic.transmissionBoost() > early);
basic.ever = 20; assert.ok(basic.transmissionBoost() > 4.5);
basic.configureSolo('curber');
const bot = new SpreaderAI(basic); bot.start();
assert.equal(basic.phase, 'running');
assert.ok(basic.counts().i >= 4);
basic.points.curber = 100;
assert.ok(basic.act('tracing', 0, 0));
assert.ok(basic.counts().iso >= 4);
assert.equal(basic.act('tracing', 0, 0), false);
assert.ok(basic.act('clinic', 0, 0));
assert.ok(basic.protectedShare() > 0.7);
const oldPoints = basic.points.curber;
basic.judge(); assert.ok(basic.points.curber > oldPoints);
console.log('Solo pacing, milestone acceleration, outbreak bootstrap, clinic, tracing and regeneration passed.');

const timedBarrier = new Outbreak({agents:Array.from({length:100},()=>({x:0,z:0}))});
timedBarrier.configureSolo('curber'); timedBarrier.phase='running'; timedBarrier.time=599;
assert.equal(timedBarrier.unlocked('barrier'),false);
timedBarrier.time=600; assert.ok(timedBarrier.available('barrier'));
timedBarrier.time=0; assert.ok(timedBarrier.unlocked('barrier'), 'Unlock remains permanent');
const {roundDuration} = await import('../src/game-runtime.js');
assert.equal(roundDuration(true),180); assert.equal(roundDuration(false),180);
console.log('Three-minute solo rounds and guaranteed early barrier unlock passed.');

for (const width of [800, 1100, 1440, 1920]) {
  setSinglePlayer(true,'curber');
  const r=gameRect('curber',width,1000);
  assert.equal(sideAt(r.x+r.width/2,r.y+r.height/2,width,1000),'curber');
  assert.equal(sideAt(r.x+r.width+1,r.y+10,width,1000),null);
  assert.equal(sideAt(r.x+r.width/2,r.y+r.height+1,width,1000),null);
  if(width>=1100) {
    assert.equal(r.x+r.width/2,width/2,'Solo map is centered in the window');
    assert.equal(r.height,888,'Solo map uses the full space below the header');
  }
}
setSinglePlayer(false);
console.log('Centered solo map, responsive controls and map input boundaries passed.');
